// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Per-resource counts (Requirements: inventory is per player). Named fields, not an array indexed
 * by resource id: only four resource kinds exist and will not grow within this game
 * (`docs/spec/reference-game.md` fixes the list), so a fixed struct reads better than a `[u32; N]`
 * the caller has to remember the index convention for. `TS` (M20b step 3): also `Ui.inventory`'s
 * own field type, read straight off the replicated `RefPlayer` -- one shape for both purposes.
 */
export type Inventory = { iron: number, wood: number, stone: number, coal: number, };
