// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Per-item counts (Requirements: inventory is per player): a fixed array indexed by
 * [`content::ItemId`] (M32: plain data, no `Vec`). `TS`: also `Ui.inventory`'s own field type and
 * `UiRecipe::cost`'s, one shape for all three.
 */
export type Inventory = [number, number, number, number, number, number];
