// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Step 1 placeholder (Scope: "no-op rules"). Replaced wholesale in step 4 by the real
 * `Action::{StartCollect, CancelCollect}` (see this brief's Deviations for the exact shape once
 * written).
 */
export type RefAction = "Noop";
