// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TileXY } from "./TileXY.js";
import type { WorldXY } from "./WorldXY.js";

/**
 * `Action::{StartCollect, CancelCollect}` (Scope; 0001's own reference-game example, verbatim
 * field shape). `#[ts(export)]`: without it ts-rs's derive macro writes no `export_bindings_*`
 * test at all (`add-action-type` skill).
 */
export type RefAction = { "StartCollect": { tile: TileXY, from: WorldXY, } } | "CancelCollect";
