// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Seed-independent knobs (Scope: "octave counts, scales, sea level, per-resource density").
 * Step 1 has no fields yet (nothing to configure about a flat world); step 2 fills these in.
 */
export type RefParams = Record<symbol, never>;
