// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Step 1 placeholder; step 4 replaces it with the real `Reject`.
 */
export type RefReject = "Unknown";
