// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `Reject` (Scope). `NoResource`/`OutOfRange`/`Busy` are `rules::collect::start`'s own three
 * rejection reasons, in the same order Scope validates them (minus "tile readable", which is
 * `Unknown`).
 */
export type RefReject = "Unknown" | "NoResource" | "OutOfRange" | "Busy";
