// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Inventory } from "./Inventory.js";
import type { TileXY } from "./TileXY.js";
import type { UiCollecting } from "./UiCollecting.js";
import type { UiCrafting } from "./UiCrafting.js";
import type { UiFurnace } from "./UiFurnace.js";
import type { UiInRange } from "./UiInRange.js";
import type { UiRecipe } from "./UiRecipe.js";

/**
 * `Ui { me, inventory, collecting, in_range, spawn }` (Scope, M20b steps 3 and 5). `me` is a raw
 * `u32`, not `engine::game::PlayerId` (same reason as [`UiCollecting::done_at`]: `PlayerId` has no
 * `TS` impl). `Default` reserves `in_range`'s capacity once ([`MAX_IN_RANGE`]); `RefClient::ui`
 * clears and refills it every call, so steady state allocates nothing (Scope, verbatim). `spawn`
 * (step 5, Scope: "publishes it as `Ui.spawn`") is the nearest land tile to the origin, computed
 * once at `RefClient` construction (`client.rs`'s own `nearest_land_tile`) and copied in unchanged
 * on every `ui()` call -- it never changes for the life of a client, so it is not itself a
 * per-frame value (the `Ui` rule, `games/reference/CLAUDE.md`).
 */
export type RefUi = { me: number, inventory: Inventory, collecting: UiCollecting | null, in_range: Array<UiInRange>, spawn: TileXY, 
/**
 * M32: the player's unlock bitset, the in-flight craft, and the unlocked recipes only.
 */
unlocks: number, crafting: UiCrafting | null, recipes: Array<UiRecipe>, 
/**
 * M33: construction mode is on (client-local, `content::local::PLACE_MODE`).
 */
placing: boolean, 
/**
 * M33: the inventory holds a furnace item (shows the Build button).
 */
can_build: boolean, 
/**
 * M33b: the furnace whose panel is open (`RefClient::open`), `None` when none or it is gone.
 */
furnace: UiFurnace | null, };
