// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A tile coordinate, plain data (`Action` must stay `Codec + TS`; not `engine::world::TilePos`,
 * which derives neither `Serialize` nor `TS` -- the same reason `fixtures/presence`'s own
 * `TileXY` exists).
 */
export type TileXY = { x: number, y: number, };
