// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TileXY } from "./TileXY.js";

/**
 * `Ui.collecting`'s own shape (M20b step 3, Scope: "`collecting: Option<{ tile, done_at }>`"): not
 * [`Collecting`] itself, which carries `done_at: engine::time::Tick` -- `Tick` has no `TS` impl (a
 * bug fix to the engine crate is out of this milestone's scope, Files touched), so the UI-facing
 * mirror carries the raw tick number instead. The client reconstructs remaining time itself from
 * `done_at` and `client.clock()` (0003 "How the UI observes state": "progress bars are derived
 * from a `done_at` tick in `Ui` and `client.clock()`").
 */
export type UiCollecting = { tile: TileXY, done_at: number, };
