// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * An in-flight craft as `Ui` shows it (`UiCollecting`'s own reasoning: raw `done_at` tick number).
 */
export type UiCrafting = { recipe: number, done_at: number, };
