// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TileXY } from "./TileXY.js";

/**
 * The open furnace as the panel reads it (M33b): its anchor tile and the six state fields, with
 * `smelt_done_at` as a raw tick number (`UiCollecting::done_at`'s reasoning).
 */
export type UiFurnace = { at: TileXY, iron_in: number, coal: number, wood: number, burn_left: number, ingots_out: number, smelt_done_at: number | null, };
