// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TileXY } from "./TileXY.js";
import type { WorldXY } from "./WorldXY.js";

/**
 * One `Ui.in_range` entry (M20b step 3, Scope: "`{ tile, resource, from }`"). `from` is the
 * player's own position when this tile entered range, refreshed only when the set of in-range
 * tiles changes (Planning decisions "Where `from` comes from") -- computed and cached by
 * `RefClient::ui` (`client.rs`), not recomputed fresh from the live spring every call.
 */
export type UiInRange = { tile: TileXY, resource: number, from: WorldXY, };
