// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Inventory } from "./Inventory.js";

/**
 * One unlocked recipe as the crafting menu lists it (M32): `cost` per item, `secs` for the
 * progress bar's label, `affordable` against the player's current inventory.
 */
export type UiRecipe = { recipe: number, cost: Inventory, secs: number, affordable: boolean, };
