// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One roster entry as `Ui.roster` shows it (M34): the engine roster joined with
 * `RefGlobal::colours`. `colour` is the player's RGB (an unassigned player reads as
 * `content::UNASSIGNED_COLOUR`), so the DOM needs no palette of its own.
 */
export type UiRosterEntry = { id: number, online: boolean, colour: [number, number, number], me: boolean, };
