// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A Q24.8 world position, plain data (same reason as [`TileXY`]; not `engine::world::WorldPos`).
 * `StartCollect`'s own witness (0001 "Witness-carrying actions"): the client's claimed position
 * when it pressed the button.
 */
export type WorldXY = { x: number, y: number, };
