// `node scripts/embed-wgsl.mjs`: reads every `src/render/wgsl/*.wgsl` file and writes the checked-in
// `src/render/wgsl.generated.ts` (docs/plan/09-renderer-terrain.md Planning decisions "Bind group
// layout": "WGSL lives in `.wgsl` files; `scripts/embed-wgsl.mjs` writes a checked-in
// `wgsl.generated.ts`, and a unit test fails when it is stale"). `generate()` is imported directly by
// `src/render/wgsl.generated.test.ts` so the freshness check never shells out to this script.
import { readdirSync, readFileSync, writeFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'

const wgslDir = fileURLToPath(new URL('../src/render/wgsl/', import.meta.url))
export const outFile = fileURLToPath(new URL('../src/render/wgsl.generated.ts', import.meta.url))

function identFor(fileName) {
  return `${fileName
    .replace(/\.wgsl$/, '')
    .replace(/[^a-zA-Z0-9]/g, '_')
    .toUpperCase()}_WGSL`
}

/** Pure: reads the current `.wgsl` sources and returns the generated file's exact text. Never
 * touches disk beyond reading `src/render/wgsl/`. */
export function generate() {
  const names = readdirSync(wgslDir)
    .filter((name) => name.endsWith('.wgsl'))
    .sort()
  const lines = [
    '// GENERATED by `node scripts/embed-wgsl.mjs` from `src/render/wgsl/*.wgsl`. Do not edit by',
    '// hand: edit the `.wgsl` source and regenerate (packages/engine/CLAUDE.md).',
  ]
  for (const name of names) {
    const source = readFileSync(`${wgslDir}${name}`, 'utf8')
    lines.push(`export const ${identFor(name)} = ${JSON.stringify(source)}`)
  }
  return `${lines.join('\n')}\n`
}

if (import.meta.url === `file://${process.argv[1]}`) {
  writeFileSync(outFile, generate())
}
