// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 0004 Decision, verbatim: `RateLimited` (admission, never reaches `apply`), `StateBudgetFull`
 * (0007 §8's check), `EngineFault` (0005 skip-record recovery). None is produced by this
 * milestone (docs/plan/12b-world-access-and-sim-driver.md Non-scope). `Serialize` (docs/plan/
 * 16-action-round-trip.md): a rejected action's result JSON (`client.onActionResult`) needs to
 * encode this half of `Rejected<G>`, tagged `{"Engine":<this>}` -- `game_instance::
 * push_result_record` keeps `Rejected<G>`'s own `Game`/`Engine` level in the JSON rather than
 * flattening it away (orchestrator ruling at the M16 gate): 0004's Decision defines `Rejected<G>`
 * as exactly this two-variant enum, and collapsing the tag would make a game's own reject variant
 * indistinguishable from the engine's by name alone once `RateLimited` (M31) and `StateBudgetFull`
 * (M21) are real. `TS` (docs/plan/16-action-round-trip.md step 4), deliberately **without**
 * `#[ts(export)]`: `EngineReject` is engine-side, not a `G::Reject`, and ts-rs's own derive macro
 * puts its `export_bindings_<type>` test in the crate that derives `TS` -- `engine` here, not a
 * downstream game crate -- so `cargo test export_bindings` run from `fixtures/puts` (0017 §5's own
 * command, scoped to that one package, no `-p`/`--workspace`) would never run it anyway; worse,
 * `#[ts(export)]` here would make *every* `cargo test -p engine` (this crate's own fast-tier
 * suite, `pnpm test rust`) write `crates/engine/bindings/EngineReject.ts` as an unwanted side
 * effect, since ts-rs generates `output_path()`/`export_all()` unconditionally and only
 * `#[ts(export)]` decides whether it *also* emits its own auto-run test (found the hard way: a
 * stray `crates/engine/bindings/` appeared after running the plain engine suite once with the
 * attribute present). `fixtures/puts/src/lib.rs` instead has its own `#[test] fn export_bindings_
 * enginereject()` that calls `<engine::sim::EngineReject as ts_rs::TS>::export_all(&Config::
 * from_env())` directly -- `export_all` needs no `#[ts(export)]` at all, so this is the same call
 * the derive macro's own generated test would have made, just written by hand in the one crate
 * whose `cargo test export_bindings` actually runs, landing `EngineReject.ts` in the fixture's own
 * `bindings/` alongside `Action`/`Reject`.
 */
export type EngineReject = 'RateLimited' | 'StateBudgetFull' | 'EngineFault'
