// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * docs/plan/16b-ui-observation-and-clock.md Scope: "`puts` gets `type Ui = PutsUi { motd, note,
 * note_until, global_ticks }`". `global_ticks` mirrors `Global::day` (the tick rule's own
 * once-a-simulated-second counter, module doc comment) -- named `_ticks` here, not `_day`, since
 * the DOM-facing name is this milestone's own to choose and a plain "day" reads oddly as a page
 * counter that advances every five seconds under `NOTE_TTL_SECS`-scale testing. `#[ts(export)]`:
 * see `Action`'s own doc comment.
 */
export type PutsUi = { motd: number; note: number; note_until: number; global_ticks: number }
