// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `From<Unknown>` (0003: "add a `?` to each read and `impl From<Unknown> for Reject`").
 * `#[ts(export)]`: see `Action`'s own doc comment.
 */
export type Reject = 'Unknown' | 'NotFound'
