// Generates a synthetic ~25k-line module so the dev-loop number isn't only for a 40-line crate.
import { writeFileSync } from 'node:fs'
const N = Number(process.argv[2] ?? 3000)
let s = '// generated by test/gen-bulk.mjs\n'
for (let i = 0; i < N; i++) {
  s += `#[inline(never)]
pub fn f${i}(cells: &mut [u32], x: u32) -> u32 {
    let n = cells.len();
    let mut acc = x.wrapping_mul(${2654435761 % (i + 7) + 3}).rotate_left(${i % 31});
    for k in 0..${(i % 5) + 2} {
        let j = (acc as usize).wrapping_add(k * ${i + 1}) % n;
        cells[j] = cells[j].wrapping_add(acc ^ ${i});
        acc = acc.wrapping_add(cells[j] >> ${(i % 7) + 1});
    }
    acc
}
`
}
s += 'pub fn run_all(cells: &mut [u32], x: u32) -> u32 {\n    let mut a = x;\n'
for (let i = 0; i < N; i++) s += `    a ^= f${i}(cells, a);\n`
s += '    a\n}\n'
writeFileSync('sim/src/bulk.rs', s)
console.log('lines:', s.split('\n').length)
